# Generated by Django 4.1.7 on 2023-03-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(db_index=True, default='Name not found', max_length=200)),
                ('prod_quantity', models.CharField(max_length=100)),
                ('prod_price', models.CharField(max_length=100)),
            ],
        ),
    ]
